// frontend/src/pages/Upload.tsx
import React, { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Card,
  Form,
  Input,
  DatePicker,
  Upload,
  Button,
  Alert,
  Progress,
  message,
  Modal,
} from 'antd';
import { InboxOutlined } from '@ant-design/icons';
import { useUpload } from '../api/hooks';
import type { UploadFile, RcFile } from 'antd/es/upload/interface';
import type { Dayjs } from 'dayjs';

const { Dragger } = Upload;
const { TextArea } = Input;

// 支持的音频/视频格式（由 ASR API 决定）
const supportedFormats: string[] = [
  'audio/mp3', 'audio/mpeg', 'audio/wav', 'audio/wave', 'audio/x-wav',
  'audio/m4a', 'audio/x-m4a', 'audio/ogg', 'audio/flac', 'audio/x-flac',
  'audio/aac', 'audio/x-aac', 'audio/opus', 'audio/webm', 'audio/amr',
  'audio/mp4', 'audio/x-ms-wma', 'audio/vnd.wave',
  'video/mp4', 'video/webm', 'video/x-matroska', 'video/x-flv',
  'video/mp2t', 'video/quicktime', 'video/x-msvideo',
];
const supportedExtensions: string[] = [
  '.3gp', '.3g2', '.8svx', '.aa', '.aac', '.aax', '.ac3', '.act', '.adp', '.adts',
  '.adx', '.aif', '.aiff', '.amr', '.ape', '.asf', '.ast', '.au', '.avr', '.caf',
  '.cda', '.dff', '.dsf', '.dsm', '.dss', '.dts', '.eac3', '.ec3', '.f32', '.f64',
  '.fap', '.flac', '.flv', '.gsm', '.ircam', '.m2ts', '.m4a', '.m4b', '.m4r',
  '.mka', '.mkv', '.mp2', '.mp3', '.mp4', '.mpc', '.mpp', '.mts', '.nut', '.nsv',
  '.oga', '.ogg', '.oma', '.opus', '.qcp', '.ra', '.ram', '.rm', '.sln', '.smp',
  '.snd', '.sox', '.spx', '.tak', '.tta', '.voc', '.w64', '.wav', '.wave', '.webm',
  '.wma', '.wve', '.wv', '.xa', '.xwma',
];

// 最大文件大小 500MB
const MAX_FILE_SIZE: number = 500 * 1024 * 1024;

// 表单值类型
interface FormValues {
  title: string;
  date?: Dayjs;
  participants?: string;
}

export default function UploadPage(): React.ReactElement {
  const navigate = useNavigate();
  const [form] = Form.useForm<FormValues>();
  const [file, setFile] = useState<File | null>(null);
  const [fileList, setFileList] = useState<UploadFile[]>([]);
  const [audioUrl, setAudioUrl] = useState<string>('');
  const [estimatedTime, setEstimatedTime] = useState<string>('');
  const audioRef = useRef<HTMLAudioElement>(null);
  
  const { uploading, progress, upload } = useUpload();

  // 格式化文件大小
  const formatFileSize = (bytes: number): string => {
    if (bytes === 0) return '0 B';
    const k: number = 1024;
    const sizes: string[] = ['B', 'KB', 'MB', 'GB'];
    const i: number = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  // 验证文件类型
  const validateFileType = (fileToValidate: RcFile): boolean => {
    const fileExtension: string = '.' + fileToValidate.name.split('.').pop()?.toLowerCase() || '';
    const isValidExtension: boolean = supportedExtensions.includes(fileExtension);
    const isValidType: boolean = supportedFormats.includes(fileToValidate.type) || isValidExtension;
    
    if (!isValidType) {
      message.error('不支持的文件格式，请上传常见音频或视频格式文件（如 MP3、WAV、AAC、FLAC、OGG、M4A、MP4、MKV 等）');
      return false;
    }
    return true;
  };

  // 验证文件大小
  const validateFileSize = (fileToValidate: RcFile): boolean => {
    if (fileToValidate.size > MAX_FILE_SIZE) {
      message.error('文件大小超过 500MB 限制');
      return false;
    }
    return true;
  };

  // 估算处理时间
  const estimateProcessingTime = (fileToEstimate: File): void => {
    try {
      const audio: HTMLAudioElement = new Audio();
      const url: string = URL.createObjectURL(fileToEstimate);
      audio.src = url;
      
      audio.onloadedmetadata = (): void => {
        const duration: number = audio.duration;
        URL.revokeObjectURL(url);
        
        const estimatedMinutes: number = Math.ceil((duration / 60) * 1.5);
        
        if (estimatedMinutes < 1) {
          setEstimatedTime('约30秒');
        } else if (estimatedMinutes < 60) {
          setEstimatedTime(`约${Math.ceil(estimatedMinutes)}分钟`);
        } else {
          const hours: number = Math.floor(estimatedMinutes / 60);
          const minutes: number = Math.ceil(estimatedMinutes % 60);
          setEstimatedTime(`约${hours}小时${minutes > 0 ? minutes + '分钟' : ''}`);
        }
      };
      
      audio.onerror = (): void => {
        URL.revokeObjectURL(url);
        setEstimatedTime('数分钟');
      };
    } catch (error) {
      console.error('估算处理时间失败:', error);
      setEstimatedTime('数分钟');
    }
  };

  // 文件变化处理
  const handleFileChange = (info: { fileList: UploadFile[] }): void => {
    const { fileList: newFileList } = info;
    setFileList(newFileList);
    
    if (newFileList.length > 0) {
      const selectedFile: UploadFile = newFileList[newFileList.length - 1];
      const rawFile: RcFile = (selectedFile.originFileObj || selectedFile) as RcFile;
      
      if (!validateFileType(rawFile)) {
        setFileList([]);
        return;
      }
      
      if (!validateFileSize(rawFile)) {
        setFileList([]);
        return;
      }
      
      setFile(rawFile);
      
      if (audioUrl) {
        URL.revokeObjectURL(audioUrl);
      }
      
      const newAudioUrl: string = URL.createObjectURL(rawFile);
      setAudioUrl(newAudioUrl);
      
      estimateProcessingTime(rawFile);
    } else {
      setFile(null);
      if (audioUrl) {
        URL.revokeObjectURL(audioUrl);
        setAudioUrl('');
      }
      setEstimatedTime('');
    }
  };

  // 重置表单
  const handleReset = (): void => {
    form.resetFields();
    setFile(null);
    setFileList([]);
    if (audioUrl) {
      URL.revokeObjectURL(audioUrl);
      setAudioUrl('');
    }
    setEstimatedTime('');
  };

  // 上传确认
  const handleUploadConfirm = async (): Promise<void> => {
    try {
      await form.validateFields();
    } catch (error) {
      return;
    }
    
    if (!file) {
      message.error('请选择要上传的音频文件');
      return;
    }
    
    Modal.confirm({
      title: '确认上传',
      content: '确认上传该音频文件？上传后将开始自动处理。',
      onOk: () => handleUpload(),
    });
  };

  // 执行上传
  const handleUpload = async (): Promise<void> => {
    try {
      const values: FormValues = await form.validateFields();
      
      const formData: FormData = new FormData();
      formData.append('audio', file as Blob);
      formData.append('title', values.title);
      if (values.date) {
        formData.append('date', values.date.format('YYYY-MM-DD'));
      }
      if (values.participants) {
        formData.append('participants', values.participants);
      }
      
      const result = await upload(formData);
      
      message.success('上传成功！');
      
      if (result.meeting_id) {
        navigate(`/meeting/${result.meeting_id}`);
      } else {
        navigate('/meetings');
      }
    } catch (error) {
      message.error((error as Error).message || '上传失败，请重试');
    }
  };

  // 组件卸载时清理
  useEffect(() => {
    return () => {
      if (audioUrl) {
        URL.revokeObjectURL(audioUrl);
      }
    };
  }, [audioUrl]);

  return (
    <div style={{ padding: 20, maxWidth: 800, margin: '0 auto' }}>
      <Card
        title="上传会议音频"
        style={{ borderRadius: 8 }}
      >
        <Form
          form={form}
          layout="vertical"
          style={{ marginTop: 20 }}
        >
          <Form.Item
            label="会议标题"
            name="title"
            rules={[
              { required: true, message: '请输入会议标题' },
              { min: 2, max: 100, message: '标题长度在 2 到 100 个字符' },
            ]}
          >
            <Input placeholder="请输入会议标题" maxLength={100} showCount />
          </Form.Item>

          <Form.Item label="会议日期" name="date">
            <DatePicker
              style={{ width: '100%' }}
              placeholder="选择会议日期"
              format="YYYY-MM-DD"
            />
          </Form.Item>

          <Form.Item label="参会人员" name="participants">
            <TextArea
              rows={2}
              placeholder="请输入参会人员，多个人员用逗号分隔"
            />
          </Form.Item>

          <Form.Item label="音频文件">
            <Dragger
              fileList={fileList}
              onChange={handleFileChange}
              beforeUpload={() => false}
              accept={supportedExtensions.join(',')}
              multiple={false}
              maxCount={1}
            >
              <p className="ant-upload-drag-icon">
                <InboxOutlined />
              </p>
              <p className="ant-upload-text">
                将音频文件拖到此处，或<em>点击上传</em>
              </p>
              <p className="ant-upload-hint">
                支持 MP3、WAV、M4A、OGG、FLAC 格式，文件大小不超过 500MB
              </p>
            </Dragger>
          </Form.Item>

          {file && (
            <div style={{ marginBottom: 20 }}>
              <Alert
                message={`已选择文件: ${file.name}`}
                description={`文件大小: ${formatFileSize(file.size)}`}
                type="info"
                showIcon
                closable={false}
              />
            </div>
          )}

          {audioUrl && (
            <div style={{ marginBottom: 20, padding: 15, backgroundColor: '#f5f7fa', borderRadius: 8 }}>
              <h4 style={{ margin: '0 0 10px 0', fontSize: 14, color: '#606266' }}>音频预览</h4>
              <audio src={audioUrl} controls style={{ width: '100%' }} ref={audioRef} />
            </div>
          )}

          {progress > 0 && (
            <div style={{ marginBottom: 20 }}>
              <Progress
                percent={progress}
                status={progress === 100 ? 'success' : undefined}
              />
              <div style={{ textAlign: 'center', marginTop: 10, fontSize: 14, color: progress === 100 ? '#67c23a' : '#606266' }}>
                {progress < 100 ? `正在上传... ${progress}%` : '上传成功！正在处理中...'}
              </div>
            </div>
          )}

          {estimatedTime && (
            <div style={{ marginBottom: 20 }}>
              <Alert
                message="预计处理时间"
                description={`根据音频时长，预计需要 ${estimatedTime} 完成处理`}
                type="warning"
                showIcon
                closable={false}
              />
            </div>
          )}

          <Form.Item style={{ marginTop: 30, textAlign: 'center' }}>
            <Button onClick={handleReset} style={{ marginRight: 10 }}>
              重置
            </Button>
            <Button
              type="primary"
              loading={uploading}
              disabled={!file || progress > 0}
              onClick={handleUploadConfirm}
            >
              {uploading ? '上传中...' : '开始上传'}
            </Button>
          </Form.Item>
        </Form>
      </Card>
    </div>
  );
}

// frontend/src/views/Upload.vue
<template>
  <div class="upload-container">
    <el-card class="upload-card">
      <template #header>
        <div class="card-header">
          <span>上传会议音频</span>
        </div>
      </template>
      
      <!-- 错误提示 -->
      <el-alert
        v-if="errorMessage"
        :title="errorMessage"
        type="error"
        :closable="true"
        @close="errorMessage = ''"
        class="error-alert"
      />
      
      <!-- 成功提示 -->
      <el-alert
        v-if="successMessage"
        :title="successMessage"
        type="success"
        :closable="true"
        @close="successMessage = ''"
        class="success-alert"
      />
      
      <el-form
        ref="formRef"
        :model="form"
        :rules="rules"
        label-width="100px"
        class="upload-form"
      >
        <!-- 会议标题 -->
        <el-form-item label="会议标题" prop="title">
          <el-input
            v-model="form.title"
            placeholder="请输入会议标题"
            maxlength="200"
            show-word-limit
            :disabled="isUploading"
          />
        </el-form-item>
        
        <!-- 会议日期 -->
        <el-form-item label="会议日期" prop="date">
          <el-date-picker
            v-model="form.date"
            type="date"
            placeholder="请选择会议日期"
            format="YYYY-MM-DD"
            value-format="YYYY-MM-DD"
            :disabled="isUploading"
          />
        </el-form-item>
        
        <!-- 参会人员 -->
        <el-form-item label="参会人员" prop="participants">
          <el-input
            v-model="form.participants"
            type="textarea"
            :rows="3"
            placeholder="请输入参会人员（多个用逗号分隔）"
            :disabled="isUploading"
          />
        </el-form-item>
        
        <!-- 音频文件上传 -->
        <el-form-item label="音频文件" prop="audio">
          <el-upload
            ref="uploadRef"
            :auto-upload="false"
            :show-file-list="true"
            :limit="1"
            :on-change="handleFileChange"
            :on-remove="handleFileRemove"
            :before-upload="beforeUpload"
            :file-list="fileList"
            :accept="ACCEPT_STRING"
            :disabled="isUploading"
            drag
          >
            <el-icon class="el-icon--upload"><upload-filled /></el-icon>
            <div class="el-upload__text">
              将文件拖到此处，或 <em>点击上传</em>
            </div>
            <template #tip>
              <div class="el-upload__tip">
                支持 MP3、WAV、M4A、OGG、FLAC、AAC、OPUS 等 70+ 种音频格式，最大 500MB
              </div>
            </template>
          </el-upload>
        </el-form-item>
        
        <!-- 上传进度 -->
        <el-form-item v-if="isUploading" label="上传进度">
          <el-progress :percentage="uploadProgress" :status="uploadProgress === 100 ? 'success' : undefined" />
        </el-form-item>
        
        <!-- 按钮区域 -->
        <el-form-item>
          <el-button
            type="primary"
            @click="handleSubmit"
            :loading="isUploading"
            :disabled="!canSubmit"
          >
            {{ isUploading ? '处理中...' : '开始处理' }}
          </el-button>
          <el-button @click="handleReset" :disabled="isUploading">
            重置
          </el-button>
        </el-form-item>
      </el-form>
      
      <!-- 处理进度提示 -->
      <div v-if="isUploading" class="processing-info">
        <el-icon class="is-loading"><loading /></el-icon>
        <span>{{ processingStatusText }}</span>
      </div>
    </el-card>
    
    <!-- 上传成功后的跳转提示 -->
    <div v-if="uploadedMeetingId" class="success-navigation">
      <el-card>
        <div class="navigation-content">
          <el-icon class="success-icon"><success-filled /></el-icon>
          <div class="text-content">
            <h3>上传成功！</h3>
            <p>会议录音正在后台处理中，您可以查看处理进度或返回列表。</p>
          </div>
          <div class="button-group">
            <el-button type="primary" @click="goToDetail">
              查看详情
            </el-button>
            <el-button @click="goToList">
              返回列表
            </el-button>
          </div>
        </div>
      </el-card>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import {
  UploadFilled,
  Loading,
  SuccessFilled
} from '@element-plus/icons-vue';
import {
  uploadMeeting,
  getUserFriendlyError,
  ApiError
} from '../api';

const router = useRouter();

// ASR_API 支持的所有音频格式
const ALLOWED_AUDIO_EXTENSIONS = [
  '3gp', '3g2', '8svx', 'aa', 'aac', 'aax', 'ac3', 'act', 'adp', 'adts',
  'adx', 'aif', 'aiff', 'amr', 'ape', 'asf', 'ast', 'au', 'avr', 'caf',
  'cda', 'dff', 'dsf', 'dsm', 'dss', 'dts', 'eac3', 'ec3', 'f32', 'f64',
  'fap', 'flac', 'flv', 'gsm', 'ircam', 'm2ts', 'm4a', 'm4b', 'm4r',
  'mka', 'mkv', 'mp2', 'mp3', 'mp4', 'mpc', 'mpp', 'mts', 'nut', 'nsv',
  'oga', 'ogg', 'oma', 'opus', 'qcp', 'ra', 'ram', 'rm', 'sln', 'smp',
  'snd', 'sox', 'spx', 'tak', 'tta', 'voc', 'w64', 'wav', 'wave', 'webm',
  'wma', 'wve', 'wv', 'xa', 'xwma'
];
const ACCEPT_STRING = '.' + ALLOWED_AUDIO_EXTENSIONS.join(',.');

// 表单引用
const formRef = ref(null);
const uploadRef = ref(null);

// 状态
const isUploading = ref(false);
const uploadProgress = ref(0);
const errorMessage = ref('');
const successMessage = ref('');
const uploadedMeetingId = ref('');
const processingStatusText = ref('正在上传文件...');

// 表单数据
const form = reactive({
  title: '',
  date: '',
  participants: '',
  audio: null
});

// 文件列表
const fileList = ref([]);

// 表单验证规则
const rules = {
  title: [
    { required: true, message: '请输入会议标题', trigger: 'blur' },
    { min: 1, max: 200, message: '会议标题长度在 1 到 200 个字符', trigger: 'blur' }
  ],
  audio: [
    { required: true, message: '请选择音频文件', trigger: 'change' }
  ]
};

// 计算属性
const canSubmit = computed(() => {
  return form.title && fileList.value.length > 0 && !isUploading.value;
});

// 文件改变（Element Plus 的 on-change 传入 uploadFile, uploadFiles）
const handleFileChange = (file, uploadFiles) => {
  form.audio = file?.raw;
  
  // 验证文件类型
  const fileName = (file?.name || '').toLowerCase();
  const fileExt = fileName.split('.').pop();
  
  if (!ALLOWED_AUDIO_EXTENSIONS.includes(fileExt)) {
    errorMessage.value = `不支持的文件格式。支持的格式: MP3、WAV、M4A、OGG、FLAC、AAC、OPUS 等共 ${ALLOWED_AUDIO_EXTENSIONS.length} 种`;
    handleFileRemove();
    return;
  }
  
  // 验证文件大小 (500MB)
  const maxSize = 500 * 1024 * 1024;
  if (file.size > maxSize) {
    errorMessage.value = '文件大小超过限制，最大允许 500MB';
    handleFileRemove();
    return;
  }
  
  // 验证通过后更新 fileList，否则 canSubmit 中的 fileList.length > 0 不满足
  fileList.value = uploadFiles || (file ? [file] : []);
  errorMessage.value = '';
};

// 文件移除
const handleFileRemove = () => {
  form.audio = null;
  fileList.value = [];
};

// 上传前检查
const beforeUpload = (file) => {
  const fileName = file.name.toLowerCase();
  const fileExt = fileName.split('.').pop();
  
  if (!ALLOWED_AUDIO_EXTENSIONS.includes(fileExt)) {
    ElMessage.error(`不支持的文件格式: ${fileExt}`);
    return false;
  }
  
  const maxSize = 500 * 1024 * 1024;
  if (file.size > maxSize) {
    ElMessage.error('文件大小超过限制，最大允许 500MB');
    return false;
  }
  
  return true;
};

// 显示错误
const showError = (error) => {
  const userMessage = getUserFriendlyError(error);
  errorMessage.value = userMessage;
  
  console.error('Upload error:', error);
};

// 提交表单
const handleSubmit = async () => {
  if (!formRef.value) return;
  
  // 验证表单
  try {
    await formRef.value.validate();
  } catch (e) {
    errorMessage.value = '请填写必要的信息';
    return;
  }
  
  if (!form.audio) {
    errorMessage.value = '请选择音频文件';
    return;
  }
  
  // 清除之前的消息
  errorMessage.value = '';
  successMessage.value = '';
  
  // 开始上传
  isUploading.value = true;
  uploadProgress.value = 0;
  processingStatusText.value = '正在上传文件...';
  uploadedMeetingId.value = '';
  
  try {
    const result = await uploadMeeting(
      form.audio,
      form.title,
      form.date,
      form.participants,
      (progress) => {
        uploadProgress.value = progress;
        if (progress < 100) {
          processingStatusText.value = `正在上传文件... ${progress}%`;
        } else {
          processingStatusText.value = '文件上传完成，正在启动处理...';
        }
      }
    );
    
    uploadProgress.value = 100;
    processingStatusText.value = '处理任务已启动！';
    successMessage.value = '上传成功！会议录音正在后台处理中。';
    
    // 保存会议ID以便后续跳转
    if (result.data && result.data.meeting_id) {
      uploadedMeetingId.value = result.data.meeting_id;
    }
    
    ElMessage.success('上传成功！');
    
  } catch (error) {
    console.error('Upload failed:', error);
    showError(error);
  } finally {
    isUploading.value = false;
  }
};

// 重置表单
const handleReset = () => {
  if (formRef.value) {
    formRef.value.resetFields();
  }
  form.date = '';
  form.participants = '';
  handleFileRemove();
  errorMessage.value = '';
  successMessage.value = '';
  uploadedMeetingId.value = '';
  uploadProgress.value = 0;
};

// 跳转到详情页
const goToDetail = () => {
  if (uploadedMeetingId.value) {
    router.push(`/meetings/${uploadedMeetingId.value}`);
  }
};

// 跳转到列表页
const goToList = () => {
  router.push('/meetings');
};
</script>

<style scoped>
.upload-container {
  max-width: 800px;
  margin: 40px auto;
  padding: 0 20px;
}

.upload-card {
  margin-bottom: 20px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: 18px;
  font-weight: bold;
}

.error-alert,
.success-alert {
  margin-bottom: 20px;
}

.upload-form {
  margin-top: 20px;
}

.processing-info {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 15px;
  background-color: #f0f9ff;
  border-radius: 4px;
  margin-top: 20px;
  color: #0066cc;
}

.processing-info .el-icon {
  font-size: 20px;
}

.success-navigation {
  margin-top: 20px;
}

.navigation-content {
  display: flex;
  align-items: center;
  gap: 20px;
  padding: 20px;
}

.success-icon {
  font-size: 48px;
  color: #67c23a;
}

.text-content {
  flex: 1;
}

.text-content h3 {
  margin: 0 0 10px 0;
  font-size: 18px;
  color: #303133;
}

.text-content p {
  margin: 0;
  color: #606266;
}

.button-group {
  display: flex;
  gap: 10px;
}

:deep(.el-upload-dragger) {
  width: 100%;
}
</style>
